### ISSUE TITLE
Unclear Error Message: bannedRoles

### ISSUE THREAD

**Issue by rktilia** [BBN-E/tac-kbp-eal#10]
When running the evaluation without evaluation before or when running a minimal example of one document output, we get the following error message:

```
bin/evaluate2016.sh param_file
.....

12:51:50.279 [main] INFO  c.b.b.c.p.s.SerifStyleParameterFileLoader - Loading parameter file /home/user/**/bender_storage/TAC/models/50/scratch/params/system_50/scoreKBPAgainstERE.params
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, com.bbn.bue.common.parameters.exceptions.MissingRequiredParameter: Missing required parameter bannedRoles
  at com.bbn.kbp.events.ScoreKBPAgainstERE$Module.getInScopePredicate(ScoreKBPAgainstERE.java:1109)
  while locating com.google.common.base.Predicate<com.bbn.kbp.events.DocLevelEventArg>
    for parameter 6 at com.bbn.kbp.events.ScoreKBPAgainstERE.<init>(ScoreKBPAgainstERE.java:158)
  while locating com.bbn.kbp.events.ScoreKBPAgainstERE

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at com.bbn.kbp.events.ScoreKBPAgainstERE.trueMain(ScoreKBPAgainstERE.java:1024)
	at com.bbn.kbp.events.ScoreKBPAgainstERE.main(ScoreKBPAgainstERE.java:1014)
Caused by: com.bbn.bue.common.parameters.exceptions.MissingRequiredParameter: Missing required parameter bannedRoles
	at com.bbn.bue.common.parameters.Parameters.getString(Parameters.java:273)
	at com.bbn.bue.common.parameters.Parameters.get(Parameters.java:329)
	at com.bbn.bue.common.parameters.Parameters.getSymbolSet(Parameters.java:900)
	at com.bbn.kbp.events.ScoreKBPAgainstERE$Module.getInScopePredicate(ScoreKBPAgainstERE.java:1109)
	at com.bbn.kbp.events.ScoreKBPAgainstERE$Module$$FastClassByGuice$$fe80cdf.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:272)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:172)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	... 3 more
```

Any ideas?

**Comment by rgabbard** [comment]
I believe this problem is fixed if you use this repository instead: https://github.com/isi-nlp/tac-kbp-eal
