### ISSUE TITLE
Unclear Error Message: Validation failed

### ISSUE THREAD

**Issue by rktilia** [BBN-E/tac-kbp-eal#9]
I am getting the following error message:

```
java.lang.RuntimeException: Validation failed for NYT_ENG_20130716.0108 with validator class com.bbn.kbp.events2014.validation.ValidatorComposer
	at com.bbn.kbp.events2014.bin.ValidateSystemOutput.checkLinkingValidity(ValidateSystemOutput.java:342)
	at com.bbn.kbp.events2014.bin.ValidateSystemOutput.validate(ValidateSystemOutput.java:227)
	at com.bbn.kbp.events2014.bin.ValidateSystemOutput.validateOnly(ValidateSystemOutput.java:121)
	at com.bbn.kbp.events2014.bin.ValidateSystemOutput2016.trueMain(ValidateSystemOutput2016.java:97)
	at com.bbn.kbp.events2014.bin.ValidateSystemOutput2016.main(ValidateSystemOutput2016.java:37)
```
I checked the docs and already excluded several possibilities as to what is going wrong. Therefore a hint concerning what this error message means and what is going wrong is greatly appreciated!

Thanks a lot for your help!

**Comment by jayded** [comment]
I would drop a debugger on the conditional statement and inspect what's going on there. 

There are two obvious possibilities: 
1. Your linking store is malformed in someway (presumably this would manifest earlier)
2. One of the validators, probably one in https://github.com/BBN-E/tac-kbp-eal/blob/master/tac-kbp-eal/src/main/java/com/bbn/kbp/events2014/validation/LinkingValidators.java crashes

(2) is more likely, and is probably easiest for you to investigate via a debugger. 

Given the time constraints left on the project we are probably not going to be able to clean up the warnings, although that sounds like it would be a good idea.

**Comment by rktilia** [comment]
In case it might be reason 1 after all, what exactly is the ResponseLinking error message referring to? Which level of the linking store might be affected? @jayded 

Thanks!

**Comment by rgabbard** [comment]
@rktilia : The exception you are seeing is because one of the linking validators rejects your linking store.  We should change it to specify which one, but may not have time to tend to this soon.  In the meantime, you can see what validators could possibly be failing in `LinkingValidators.java`. Possible causes:
* your linking store contains responses with Generic realis
* your are linking together two responses whose types are not allowed to link. What types are allowed to link is defined by the `linkableTypes` parameter provided to the validator.
